#!/usr/bin/env python3

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generate a fresh RSA keypair for JWT signing and write it to a Kubernetes Secret.
#
# Usage:
#     python3 scripts/generate_jwt_keys.py
#
# This script overwrites extras/jwt/jwt-secret.yaml with a new RSA 2048-bit keypair.
# It is idempotent - each run produces fresh keys.

import base64
import os

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.backends import default_backend

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "..", "extras", "jwt", "jwt-secret.yaml")

LICENSE_HEADER = """# Copyright 2020 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""


def generate_keypair():
    """Generate a 2048-bit RSA keypair."""
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend(),
    )
    public_key = private_key.public_key()
    return private_key, public_key


def serialize_keys(private_key, public_key):
    """Serialize keys to PEM and base64-encode them."""
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_pem = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return (
        base64.b64encode(private_pem).decode("ascii"),
        base64.b64encode(public_pem).decode("ascii"),
    )


def write_secret(private_b64, public_b64):
    """Write the Kubernetes Secret YAML to the output path."""
    yaml_content = (
        LICENSE_HEADER
        + "# This secret contains a keypair used to sign and verify JWTs for authentication.\n"
        + "# It was generated by scripts/generate_jwt_keys.py.\n"
        + "# NEVER commit real keys to version control.\n"
        + "apiVersion: v1\n"
        + "kind: Secret\n"
        + "metadata:\n"
        + "  name: jwt-key\n"
        + "type: Opaque\n"
        + "data:\n"
        + "  jwtRS256.key: " + private_b64 + "\n"
        + "  jwtRS256.key.pub: " + public_b64 + "\n"
    )
    with open(OUTPUT_PATH, "w") as f:
        f.write(yaml_content)


def main():
    private_key, public_key = generate_keypair()
    private_b64, public_b64 = serialize_keys(private_key, public_key)
    write_secret(private_b64, public_b64)
    print(f"Generated fresh RSA 2048 keypair and wrote it to {OUTPUT_PATH}")
    print("  jwtRS256.key     : private key (base64-encoded PEM)")
    print("  jwtRS256.key.pub : public key  (base64-encoded PEM)")


if __name__ == "__main__":
    main()
